apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: cache
  name: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cache
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/ctfdmaster_internal: "true"
        io.kompose.service: cache
    spec:
      containers:
        - image: redis:4
          name: cache
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: cache-claim0
      restartPolicy: Always
      volumes:
        - name: cache-claim0
          persistentVolumeClaim:
            claimName: cache-claim0
status: {}
